# Generated by Django 4.0.4 on 2022-04-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('category', models.CharField(choices=[('GE', 'General'), ('AC', 'Account'), ('ET', 'Et cetera')], max_length=2, verbose_name='카테고리')),
                ('reply', models.TextField(verbose_name='답변')),
                ('creator', models.TextField(verbose_name='생성자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('final_corr', models.TextField(verbose_name='최종 수정자')),
                ('final_corr_at', models.DateTimeField(auto_now_add=True, verbose_name='최종 수정일시')),
            ],
        ),
    ]
